' Use: https://nomuraya.tk/2022/03/revealjs_wordpress_hosting/
' Ref: https://plantuml.com/ja/deployment-diagram
@startuml

:開発者:
node ホスティングサーバー [
  ホスティングサーバー
  (https://nomuraya.tk)
]
:閲覧者:

file develop_env #palegreen;line:green;line.dashed;text:green {
rectangle cms [
  CMS
]
rectangle ビルドツール [
  ビルドツール
]
rectangle git [
  git
]
}

file Github #palegreen;line:green;line.dashed;text:green {
node ホスティングリポジトリ [
  public
  リポジトリ
]
component CI [
  Github Actions
]
node 他のHTMLリポジトリ [
  other_html
  リポジトリ
]
}

開発者 --> 他のHTMLリポジトリ
開発者 -> cms
cms -> ビルドツール
ビルドツール -> git
git --> ホスティングリポジトリ
ホスティングリポジトリ -> ホスティングサーバー
ホスティングリポジトリ -left-> CI
CI -left-> 他のHTMLリポジトリ
他のHTMLリポジトリ -> CI
CI -> ホスティングリポジトリ
閲覧者 --> ホスティングサーバー

@enduml